services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=rainlo
      - DB_USERNAME=rainlo
      - DB_PASSWORD=${DB_PASSWORD}
      - LOG_CHANNEL=stderr
      - LOG_LEVEL=debug
      - CACHE_STORE=file
      - SESSION_DRIVER=file
      - QUEUE_CONNECTION=sync
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./storage:/var/www/html/storage
      - app_cache:/var/www/html/bootstrap/cache
    networks:
      - rainlo-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rainlo
      - POSTGRES_USER=rainlo
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rainlo -d rainlo"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - rainlo-network

volumes:
  db_data:
    driver: local
  app_cache:
    driver: local

networks:
  rainlo-network:
    driver: bridge
