name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH key and test connection
        env:
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
        run: |
          mkdir -p ~/.ssh
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

          echo "👉 Starting SSH connection..."
          ssh -4 -vvv -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -p "$PORT" "$USERNAME@$HOST" exit
