name: Test SSH Connection

on:
  workflow_dispatch:

jobs:
  ssh-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test SSH connection with debug
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key -p ${{ secrets.PORT }} ${{ secrets.USERNAME }}@${{ secrets.HOST }} exit
        env:
          # If your private key is in a secret, write it to a file first
          DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        shell: bash
        # Setup the SSH key file
        run: |
          echo "$DEPLOY_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
